spring:
  contentnegotiation:
    favor-parameter: true  #开启请求参数内容协商模式
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.22.5.12:3309/zwh?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
    username: root
    password: 03283x
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl